const assetsTypes = {
    ADD_FOLDER: 'ADD_FOLDER',
    DELETE_FOLDER: 'REMOVE_FOLDER',
    UPDATE_FOLDER: 'UPDATE_FOLDER',
    UPDATE_ASSETS: 'UPDATE_ASSETS',
    DELETE_ASSET: 'DELETE_ASSET',
    UPDATE_ASSET_NAME: 'UPDATE_ASSET_NAME',
    DOWNLOAD_SLICES: 'DOWNLOAD_SLICES'
}

export default assetsTypes