version: '3.9'

services:
  server:
    build: ./server
    container_name: server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /server/images_generator
    ports:
      - "8000:8000"
  client:
    build: ./client
    container_name: client
    volumes:
      - /client/node_modules
      - /client/build
    command: yarn start:server
    ports:
      - "3000:3000"