const actionTypes = {
    UPDATE_META_NAME: 'UPDATE_META_NAME', 
    UPDATE_META_SYMBOL: 'UPDATE_META_SYMBOL',
    UPDATE_META_DESCRIPTION: 'UPDATE_META_DESCRIPTION',
    UPDATE_META_SELLER: 'UPDATE_META_SELLER',
    UPDATE_META_COLLECTION_NAME: 'UPDATE_META_COLLECTION_NAME',
    UPDATE_META_COLLECTION_FAMILY: 'UPDATE_META_COLLECTION_FAMILY',
    UPDATE_META_PROPERTIES_CATEGORY: 'UPDATE_META_PROPERTIES_CATEGORY',
    UPDATE_META_PROPERTIES_CREATORS: 'UPDATE_META_PROPERTIES_CREATORS',
    REMOVE_META_PROPERTIES_CREATORS: 'REMOVE_META_PROPERTIES_CREATORS',
    ADD_META_PROPERTIES_CREATORS: 'ADD_META_PROPERTIES_CREATORS',
    UPLOAD_META: 'UPLOAD_META'
}

export default actionTypes