const algTypes = {
    UPDATE_IMAGES_COUNT: 'UPDATE_IMAGES_COUNT',
    UPDATE_IMAGE_SIZE: 'UPDATE_IMAGE_WIDTH',
    UPDATE_TIMEOUT: 'UPDATE_TIMEOUT',
    UPDATE_SEQUENCES_UNIQUE: 'UPDATE_SEQUENCES_UNIQUE',
    UPDATE_BACKGROUND_COLOR: 'UPDATE_BACKGROUND_COLOR',
    UPLOAD_CONF: 'UPLOAD_CONF'
}

export default algTypes